### ISSUE TITLE
Enabling support for showing window after process put to sleep (SDL2)

### ISSUE THREAD

**Issue by bjadamson** [wmcbrine/PDCurses#144]
I'm adding support for the user to hit "ctrl-z" to put the application to sleep in the game I'm making using pdcurses. To get the window to show again after trying to wake up the process, I added the patched pdcdisp.c with the following:

```C++
diff --git a/source/external/curses/sdl2/pdcdisp.c b/source/external/curses/sdl2/pdcdisp.c
index a3c27163..102ba17b 100644
--- a/source/external/curses/sdl2/pdcdisp.c
+++ b/source/external/curses/sdl2/pdcdisp.c
@@ -571,6 +571,9 @@ void PDC_pump_and_peep(void)
             (SDL_WINDOWEVENT_RESTORED == event.window.event ||
              SDL_WINDOWEVENT_EXPOSED == event.window.event))
         {
+            pdc_screen = SDL_GetWindowSurface(pdc_window);
+            SDL_ShowWindow(pdc_window);
+
             SDL_UpdateWindowSurface(pdc_window);
             rectcount = 0;
         }
```

<s>Without the call to `pdc_screen = SDL_GetWindowSurface(pdc_window);` before the call to `SDL_ShowWindow(pdc_window)`  the window never re-appears. I checked the [documentation](https://wiki.libsdl.org/SDL2/SDL_GetWindowSurface) and it says that the call is necessary whenever a resize event happens. This behavior seems to imply to me that RESTORED or EXPOSED events are resized events somehow.</s>

I realize the README.md says that pdcurses will ignore resize events, but I'm wondering if you'd be willing to help me add support for this use case.

edit: Ok I did some more digging into my own code, it turns out I was doing something else wrong and don't actually need the call to SDL_GetWindowSurface.

Only the call to SDL_ShowWindow is necessary.

**Comment by bjadamson** [comment]
OK adding this for my own information,

when I re-open the app using "fg" from the command-line, I see the following backtrace:

```
#0  SDL_SetError_REAL (fmt=0x7ffff7f4b1c0 "Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface") at /usr/src/debug/
SDL2-2.26.3-1.fc38.x86_64/src/SDL_error.c:32
#1  0x0000000000640e36 in PDC_update_rects () at /home/badamson/projects/rrogue/source/external/curses/sdl2/pdcdisp.c:66
#2  0x0000000000641f69 in PDC_doupdate () at /home/badamson/projects/rrogue/source/external/curses/sdl2/pdcdisp.c:561
#3  0x000000000063a9c0 in doupdate () at /home/badamson/projects/rrogue/source/external/curses/pdcurses/refresh.c:218
#4  0x000000000063aa89 in wrefresh (win=0x17a6d50) at /home/badamson/projects/rrogue/source/external/curses/pdcurses/refresh.c:242
#5  0x000000000062edab in platform::draw::update(CWinfo const&)::$_0::operator()() const (this=0x7fffffffa958) at /home/badamson/projects/rrogue/s
ource/platform/curses/common/draw.cxx:54
#6  0x000000000062ed7a in platform::draw::update(CWinfo const&) (window=...) at /home/badamson/projects/rrogue/source/platform/curses/common/draw.
cxx:54
#7  0x000000000060c728 in (anonymous namespace)::print_status(CWinfo const&, Player const&)::$_0::operator()() const (this=0x7fffffffaa48) at /hom
e/badamson/projects/rrogue/source/game/ui.cxx:109
#8  0x000000000060c538 in core::impl::DestroyFN<(anonymous namespace)::print_status(CWinfo const&, Player const&)::$_0&&>::~DestroyFN() (this=0x7f
ffffffaa40) at /home/badamson/projects/rrogue/source/core/macro/scope_exit.hpp:24
#9  0x000000000060ba70 in (anonymous namespace)::print_status(CWinfo const&, Player const&) (window=..., player=...) at /home/badamson/projects/rr
ogue/source/game/ui.cxx:137
#10 0x000000000060b81d in ui::render(MainWindows const&, Rogue&) (mainw=..., rogue=...) at /home/badamson/projects/rrogue/source/game/ui.cxx:199
#11 0x000000000060786d in (anonymous namespace)::draw_game(MainWindows&, Rogue&) (mainw=..., rogue=...) at /home/badamson/projects/rrogue/source/g
ame/turn.cxx:140
#12 0x0000000000606daf in (anonymous namespace)::command(CWindows&, Rogue&, CommandState&) (windows=..., rogue=..., cs=...) at /home/badamson/proj
ects/rrogue/source/game/turn.cxx:479
#13 0x0000000000606a1a in do_turn(CWindows&, Rogue&, CommandState&) (windows=..., rogue=..., cs=...) at /home/badamson/projects/rrogue/source/game
/turn.cxx:548
#14 0x000000000040bad5 in (anonymous namespace)::playit(CWindows&, Rogue&) (windows=..., rogue=...) at /home/badamson/projects/rrogue/source/game/
main.cxx:316
#15 0x000000000040b10a in main(int, char**) (argc=1, argv=0x7fffffffdeb8) at /home/badamson/projects/rrogue/source/game/main.cxx:504
```

Line's 0-4 are from inside pdcurses lib.

**Comment by bjadamson** [comment]
I did some more digging ... it turns out this issue only happens when SDL_WINDOW_FULLSCREEN_DESKTOP is enabled during window creation. This is just a bug in my sdl version it seems.

**Comment by bjadamson** [comment]
Thanks for your help here. :+1:
